[package]
name = "sparkling-bootcamp-exercise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambdaworks-math = { git="https://github.com/lambdaclass/lambdaworks.git" }
hex = "0.4.3"